version: '3.2'

services:

  nginx:
    image: nginx:alpine
    read_only: true
    ports:
    - "8080:80"
    volumes:
    - ./ui/web/:/usr/share/nginx/html/:ro
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    tmpfs:
    - /var/cache/nginx/
    - /var/run/

  restcount:
    image: francescou/rest-count
    read_only: true

  restip:
    image: francescou/rest-ip
    read_only: true

  redis:
    image: redis:3.2.0-alpine
    read_only: true

  mongo:
    image: mongo:3.3.6
    read_only: true
    tmpfs:
    - /tmp/
