consul:
  image: gliderlabs/consul-server:0.6
  ports:
  - "8500:8500"
  command: -server -bootstrap 
  hostname: node1

nginx:
  build: nginx
  ports:
  - "8080:80"
  links:
  - "consul:consul"
  - "ui:ui"
  volumes:
  - ./nginx/logs/:/var/log/nginx

ui:
  build: ui

restcountprimary:
  image: rest-count
  environment:
  - TAGS=primary
  links:
  - "consul:consul"
  - "redis:redis"

restcountbackup:
  image: rest-count
  environment:
  - TAGS=backup
  links:
  - "consul:consul"
  - "redis:redis"

restipprimary:
  image: rest-ip
  environment:
  - TAGS=primary
  links:
  - "consul:consul"
  - "mongo:mongo"

restipbackup:
  image: rest-ip
  environment:
  - TAGS=backup
  links:
  - "consul:consul"
  - "mongo:mongo"

redis:
  image: redis:3.0.3

mongo:
  image: mongo:2.6.11
