consul:
  image: consul:v0.6.4
  ports:
  - "8500:8500"
  command: agent -dev -client 0.0.0.0

nginx:
  build: nginx
  ports:
  - "8080:80"
  links:
  - "consul:consul"
  - "ui:ui"
  volumes:
  - ./nginx/logs/:/var/log/nginx

ui:
  build: ui

restcountprimary:
  image: rest-count
  environment:
  - TAGS=primary
  links:
  - "consul:consul"
  - "redis:redis"

restcountbackup:
  image: rest-count
  environment:
  - TAGS=backup
  links:
  - "consul:consul"
  - "redis:redis"

restipprimary:
  image: rest-ip
  environment:
  - TAGS=primary
  links:
  - "consul:consul"
  - "mongo:mongo"

restipbackup:
  image: rest-ip
  environment:
  - TAGS=backup
  links:
  - "consul:consul"
  - "mongo:mongo"

redis:
  image: redis:3.2.0-alpine

mongo:
  image: mongo:3.3.6
